name: PHP Custom Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: crud
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install MySQL client
        run: sudo apt-get install -y default-mysql-client

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Set up database
        env:
          DB_HOST: 127.0.0.1
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: crud
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < src/schema.sql

      - name: Insert test data
        env:
          DB_HOST: 127.0.0.1
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: crud
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME -e "
          INSERT INTO user (nome_var_user, email_var_user, password_var_user) 
          VALUES ('Test User', 'test@example.com', 'password123');"

      - name: Run Read Test
        env:
          DB_HOST: 127.0.0.1
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: crud
        run: php src/readTest.php
